{% set name = "goodvibes" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b2a7b5201d9e5343ae351ed47e3c7efcf745e959e75ff5cc0a1d587b728da77

build:
  number: 0
  noarch: python
  entry_points:
    - goodvibes = goodvibes.GoodVibes:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64
  run:
    - python >=3.9
    - numpy
    - pymsym
    - rich >=13

test:
  imports:
    - goodvibes
    - goodvibes.GoodVibes
    - goodvibes.thermo
    - goodvibes.pes
  requires:
    - pip
  commands:
    - pip check
    - goodvibes --help

about:
  home: https://github.com/patonlab/goodvibes
  license: MIT
  license_file: LICENSE.txt
  summary: A python program to compute corrections to thermochemical data from frequency calculations
  dev_url: https://github.com/patonlab/goodvibes

extra:
  recipe-maintainers:
    - luchini18
    - bobbypaton
