{% set name = "goodvibes" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3cb7d4679b12440833f6add0e283190db53e31e5aea95f0a8e3c734b73da57e

build:
  number: 0
  entry_points:
    - goodvibes = goodvibes.GoodVibes:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - cclib
    - numpy
    - python

test:
  imports:
    - goodvibes
    - goodvibes.GoodVibes
    - goodvibes.thermo
    - goodvibes.pes
  requires:
    - pip
  commands:
    - pip check
    - goodvibes --help

about:
  home: https://github.com/patonlab/goodvibes
  license: MIT
  license_file:
    - LICENSE.txt # GoodVibes license
    - symmetry.LICENSE.txt # Symmetry license
  summary: A python program to compute corrections to thermochemical data from frequency calculations

extra:
  recipe-maintainers:
    - luchini18
