{% set name = "goodvibes" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24d8d7a2671de88c67463da83f82a7d58efd7b70cc45db965b55e6b6489a0433

build:
  number: 0
  entry_points:
    - goodvibes = goodvibes.GoodVibes:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - cclib
    - numpy
    - python

test:
  imports:
    - goodvibes
    - goodvibes.GoodVibes
    - goodvibes.thermo
    - goodvibes.pes
  requires:
    - pip
  commands:
    - pip check
    - goodvibes --help

about:
  home: https://github.com/patonlab/goodvibes
  license: MIT
  license_file:
    - LICENSE.txt # GoodVibes license
    - symmetry.LICENSE.txt # Symmetry license
  summary: A python program to compute corrections to thermochemical data from frequency calculations

extra:
  recipe-maintainers:
    - luchini18
